---
- block:
    - name: Update apt cache
      when: apt_cache_prepull_enabled and ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - setup-all
    - install-all
